from app import app, db
from models import Product

def seed_products():
    with app.app_context():
        # Clear existing products
        Product.query.delete()
        
        products = [
            # Vegetables (30 items)
            Product(name='Sukuma Wiki Fresh (Kale)', category='vegetables', price=30, stock=200, description='Fresh sukuma wiki from local farms', image_url='https://images.unsplash.com/photo-1580910051074-3eb694886505?w=400'),
            Product(name='Spinach Organic', category='vegetables', price=40, stock=180, description='Organic spinach leaves', image_url='https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400'),
            Product(name='Cabbage Whole Head', category='vegetables', price=50, stock=160, description='Fresh cabbage head', image_url='https://images.unsplash.com/photo-1594282557735-de1f8f0f574a?w=400'),
            Product(name='Tomatoes Fresh (1kg)', category='vegetables', price=80, stock=250, description='Ripe juicy tomatoes', image_url='https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=400'),
            Product(name='Red Onions (1kg)', category='vegetables', price=60, stock=300, description='Fresh red onions', image_url='https://images.unsplash.com/photo-1580201092675-a0a6a6cafbb1?w=400'),
            Product(name='Carrots Sweet (1kg)', category='vegetables', price=70, stock=200, description='Sweet crunchy carrots', image_url='https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=400'),
            Product(name='Irish Potatoes (2kg)', category='vegetables', price=120, stock=280, description='Fresh Irish potatoes', image_url='https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400'),
            Product(name='Green Bell Pepper', category='vegetables', price=20, stock=190, description='Fresh green bell peppers', image_url='https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400'),
            Product(name='Cucumber Fresh', category='vegetables', price=25, stock=170, description='Fresh cucumbers', image_url='https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=400'),
            Product(name='Lettuce Crispy', category='vegetables', price=35, stock=160, description='Crispy lettuce', image_url='https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=400'),
            Product(name='Broccoli Fresh', category='vegetables', price=90, stock=140, description='Fresh broccoli', image_url='https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=400'),
            Product(name='Cauliflower White', category='vegetables', price=85, stock=145, description='White cauliflower', image_url='https://images.unsplash.com/photo-1568584711271-0c9dc6c027d8?w=400'),
            Product(name='Dhania Fresh Bunch', category='vegetables', price=20, stock=220, description='Fresh dhania bunch', image_url='https://images.unsplash.com/photo-1612169676931-cccc961e2888?w=400'),
            Product(name='Spring Onions Bundle', category='vegetables', price=25, stock=200, description='Fresh spring onions', image_url='https://images.unsplash.com/photo-1604152135912-04a022e23696?w=400'),
            Product(name='Garlic Bulbs (250g)', category='vegetables', price=150, stock=180, description='Fresh garlic bulbs'),
            Product(name='Ginger Root (250g)', category='vegetables', price=120, stock=190, description='Fresh ginger root'),
            Product(name='Beetroot Fresh', category='vegetables', price=60, stock=150, description='Fresh beetroots'),
            Product(name='Sweet Potato Orange (1kg)', category='vegetables', price=80, stock=200, description='Orange sweet potatoes'),
            Product(name='Pumpkin Whole', category='vegetables', price=100, stock=140, description='Fresh pumpkin'),
            Product(name='Eggplant (Biringanya)', category='vegetables', price=45, stock=160, description='Fresh eggplant'),
            Product(name='Red Bell Pepper', category='vegetables', price=30, stock=150, description='Sweet red peppers'),
            Product(name='Yellow Bell Pepper', category='vegetables', price=30, stock=140, description='Fresh yellow peppers'),
            Product(name='Zucchini Fresh', category='vegetables', price=50, stock=120, description='Fresh zucchini'),
            Product(name='Mushrooms (250g)', category='vegetables', price=180, stock=100, description='Button mushrooms'),
            Product(name='Baby Corn (pack)', category='vegetables', price=120, stock=130, description='Fresh baby corn'),
            Product(name='Green Beans (500g)', category='vegetables', price=90, stock=140, description='French beans'),
            Product(name='Peas Fresh (500g)', category='vegetables', price=100, stock=120, description='Garden peas'),
            Product(name='Leeks Fresh', category='vegetables', price=60, stock=110, description='Fresh leeks'),
            Product(name='Celery Fresh', category='vegetables', price=70, stock=100, description='Fresh celery'),
            Product(name='Arrowroots (1kg)', category='vegetables', price=110, stock=150, description='Fresh arrowroots'),
            
            # Fruits (30 items)
            Product(name='Bananas Sweet (1 dozen)', category='fruits', price=120, stock=250, description='Sweet ripe bananas', image_url='https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400'),
            Product(name='Red Apples (1kg)', category='fruits', price=250, stock=200, description='Red crispy apples', image_url='https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400'),
            Product(name='Juicy Oranges (1kg)', category='fruits', price=150, stock=220, description='Juicy oranges', image_url='https://images.unsplash.com/photo-1547514701-42782101795e?w=400'),
            Product(name='Kenya Mangoes', category='fruits', price=50, stock=300, description='Sweet Kenya mangoes', image_url='https://images.unsplash.com/photo-1553279768-865429fa0078?w=400'),
            Product(name='Watermelon Large', category='fruits', price=200, stock=180, description='Fresh watermelon', image_url='https://images.unsplash.com/photo-1589984662646-e7b2e4962f18?w=400'),
            Product(name='Pineapple Sweet', category='fruits', price=100, stock=190, description='Sweet pineapple', image_url='https://images.unsplash.com/photo-1550828520-4cb496926fc9?w=400'),
            Product(name='Papaya Ripe (Pawpaw)', category='fruits', price=80, stock=170, description='Ripe papaya', image_url='https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?w=400'),
            Product(name='Avocado Hass', category='fruits', price=30, stock=250, description='Fresh avocados', image_url='https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400'),
            Product(name='Passion Fruit (6 pcs)', category='fruits', price=60, stock=200, description='Sweet passion fruits', image_url='https://images.unsplash.com/photo-1520787497953-1985ca467702?w=400'),
            Product(name='Seedless Grapes (500g)', category='fruits', price=180, stock=160, description='Seedless grapes', image_url='https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=400'),
            Product(name='Strawberries Fresh (250g)', category='fruits', price=200, stock=150, description='Fresh strawberries', image_url='https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400'),
            Product(name='Lemon Fresh (4 pcs)', category='fruits', price=40, stock=220, description='Fresh lemons', image_url='https://images.unsplash.com/photo-1590502593747-42a996133562?w=400'),
            Product(name='Tangerines (1kg)', category='fruits', price=130, stock=180, description='Sweet tangerines'),
            Product(name='Plums (500g)', category='fruits', price=150, stock=160, description='Juicy plums'),
            Product(name='Pears Sweet (1kg)', category='fruits', price=220, stock=150, description='Sweet pears'),
            Product(name='Guava Fresh', category='fruits', price=25, stock=200, description='Fresh guavas'),
            Product(name='Coconut Fresh', category='fruits', price=80, stock=170, description='Fresh coconut'),
            Product(name='Tree Tomato (Tamarillo)', category='fruits', price=100, stock=160, description='Fresh tree tomatoes'),
            Product(name='Sugar Cane (piece)', category='fruits', price=40, stock=190, description='Sweet sugarcane'),
            Product(name='Custard Apple', category='fruits', price=50, stock=150, description='Ripe custard apple'),
            Product(name='Green Apples (1kg)', category='fruits', price=260, stock=180, description='Granny smith apples'),
            Product(name='Dragon Fruit', category='fruits', price=120, stock=100, description='Exotic dragon fruit'),
            Product(name='Kiwi Fruit (4 pcs)', category='fruits', price=200, stock=120, description='Fresh kiwi'),
            Product(name='Pomegranate', category='fruits', price=150, stock=110, description='Fresh pomegranate'),
            Product(name='Blueberries (125g)', category='fruits', price=280, stock=80, description='Fresh blueberries'),
            Product(name='Blackberries (125g)', category='fruits', price=250, stock=70, description='Fresh blackberries'),
            Product(name='Cherries (250g)', category='fruits', price=350, stock=60, description='Sweet cherries'),
            Product(name='Dates (250g)', category='fruits', price=180, stock=140, description='Sweet dates'),
            Product(name='Figs Fresh (pack)', category='fruits', price=200, stock=90, description='Fresh figs'),
            Product(name='Star Fruit', category='fruits', price=80, stock=100, description='Star shaped fruit'),
            
            # Meat (20 items)
            Product(name='Beef Steak Premium (500g)', category='meat', price=400, stock=150, description='Premium beef steak'),
            Product(name='Beef Stew Cut (1kg)', category='meat', price=600, stock=160, description='Beef for stewing'),
            Product(name='Minced Beef (500g)', category='meat', price=300, stock=180, description='Fresh minced beef'),
            Product(name='Beef Soup Bones (1kg)', category='meat', price=200, stock=170, description='Beef bones for soup'),
            Product(name='Goat Meat Fresh (1kg)', category='meat', price=800, stock=140, description='Fresh goat meat'),
            Product(name='Mutton Fresh (1kg)', category='meat', price=750, stock=135, description='Fresh mutton'),
            Product(name='Pork Chops (500g)', category='meat', price=350, stock=140, description='Pork chops'),
            Product(name='Beef Sausages (500g)', category='meat', price=280, stock=190, description='Beef sausages'),
            Product(name='Smoked Bacon (250g)', category='meat', price=300, stock=160, description='Smoked bacon'),
            Product(name='Beef Liver Fresh (500g)', category='meat', price=250, stock=150, description='Fresh beef liver'),
            Product(name='Tripe Matumbo (500g)', category='meat', price=180, stock=160, description='Fresh beef tripe'),
            Product(name='Beef Ribs (1kg)', category='meat', price=550, stock=145, description='Beef ribs'),
            Product(name='Cocktail Smokies (500g)', category='meat', price=250, stock=200, description='Cocktail sausages'),
            Product(name='Corned Beef Can (340g)', category='meat', price=280, stock=180, description='Canned corned beef'),
            Product(name='Sliced Salami (200g)', category='meat', price=320, stock=150, description='Sliced salami'),
            Product(name='Beef Burger Patties (pack 4)', category='meat', price=350, stock=140, description='Beef patties'),
            Product(name='Lamb Chops (500g)', category='meat', price=650, stock=100, description='Fresh lamb chops'),
            Product(name='Beef T-Bone (500g)', category='meat', price=500, stock=120, description='T-bone steak'),
            Product(name='Beef Fillet (500g)', category='meat', price=600, stock=110, description='Beef fillet'),
            Product(name='Pork Belly (500g)', category='meat', price=380, stock=130, description='Fresh pork belly'),
            
            # Poultry (15 items)
            Product(name='Whole Chicken Fresh (1.5kg)', category='poultry', price=650, stock=180, description='Fresh whole chicken'),
            Product(name='Chicken Breasts Boneless (500g)', category='poultry', price=350, stock=200, description='Boneless chicken breasts'),
            Product(name='Chicken Thighs (1kg)', category='poultry', price=450, stock=190, description='Fresh chicken thighs'),
            Product(name='Chicken Wings (1kg)', category='poultry', price=400, stock=180, description='Fresh chicken wings'),
            Product(name='Chicken Drumsticks (1kg)', category='poultry', price=420, stock=185, description='Fresh drumsticks'),
            Product(name='Chicken Gizzards (500g)', category='poultry', price=200, stock=160, description='Fresh chicken gizzards'),
            Product(name='Farm Eggs Tray (30)', category='poultry', price=450, stock=250, description='Fresh farm eggs'),
            Product(name='Whole Turkey', category='poultry', price=1800, stock=60, description='Whole turkey'),
            Product(name='Duck Whole Fresh', category='poultry', price=1200, stock=45, description='Fresh whole duck'),
            Product(name='Quail Eggs (12)', category='poultry', price=180, stock=140, description='Fresh quail eggs'),
            Product(name='Chicken Mince (500g)', category='poultry', price=280, stock=160, description='Minced chicken'),
            Product(name='Chicken Livers (500g)', category='poultry', price=180, stock=140, description='Chicken livers'),
            Product(name='Chicken Sausages (500g)', category='poultry', price=300, stock=170, description='Chicken sausages'),
            Product(name='Smoked Chicken (whole)', category='poultry', price=900, stock=80, description='Smoked chicken'),
            Product(name='Turkey Sausages (500g)', category='poultry', price=380, stock=120, description='Turkey sausages'),
            
            # Fish (15 items)
            Product(name='Tilapia Fresh (1kg)', category='fish', price=600, stock=170, description='Fresh tilapia fish'),
            Product(name='Nile Perch Fresh (1kg)', category='fish', price=700, stock=150, description='Fresh Nile perch'),
            Product(name='Salmon Fillet (500g)', category='fish', price=900, stock=130, description='Fresh salmon fillet'),
            Product(name='Tuna Canned (200g)', category='fish', price=180, stock=220, description='Canned tuna'),
            Product(name='Sardines Canned', category='fish', price=120, stock=250, description='Canned sardines'),
            Product(name='Fresh Prawns (500g)', category='fish', price=800, stock=140, description='Fresh prawns'),
            Product(name='Octopus Fresh (500g)', category='fish', price=650, stock=130, description='Fresh octopus'),
            Product(name='Squid Fresh (500g)', category='fish', price=600, stock=135, description='Fresh squid'),
            Product(name='Mackerel Canned', category='fish', price=140, stock=200, description='Canned mackerel'),
            Product(name='Omena Dry (500g)', category='fish', price=150, stock=190, description='Dried silver fish'),
            Product(name='Catfish Fresh (1kg)', category='fish', price=550, stock=120, description='Fresh catfish'),
            Product(name='Crab Fresh (500g)', category='fish', price=700, stock=100, description='Fresh crab'),
            Product(name='Lobster (500g)', category='fish', price=1200, stock=60, description='Fresh lobster'),
            Product(name='Mussels (500g)', category='fish', price=400, stock=110, description='Fresh mussels'),
            Product(name='Fish Fingers (pack)', category='fish', price=280, stock=160, description='Breaded fish fingers'),
            
            # Dairy (20 items)
            Product(name='Fresh Milk (1L)', category='dairy', price=120, stock=300, description='Fresh cow milk'),
            Product(name='Mala Fermented (500ml)', category='dairy', price=60, stock=250, description='Fermented milk'),
            Product(name='Fruit Yogurt (500ml)', category='dairy', price=100, stock=220, description='Fruit yogurt'),
            Product(name='Cheddar Cheese (200g)', category='dairy', price=250, stock=180, description='Cheddar cheese'),
            Product(name='Salted Butter (500g)', category='dairy', price=350, stock=190, description='Salted butter'),
            Product(name='Blue Band Margarine (500g)', category='dairy', price=180, stock=250, description='Blue band margarine'),
            Product(name='Fresh Cream (250ml)', category='dairy', price=150, stock=160, description='Fresh cream'),
            Product(name='Buttermilk (500ml)', category='dairy', price=80, stock=170, description='Fresh buttermilk'),
            Product(name='Pure Ghee (500ml)', category='dairy', price=400, stock=150, description='Pure ghee'),
            Product(name='Powdered Milk (1kg)', category='dairy', price=550, stock=200, description='Full cream milk powder'),
            Product(name='Vanilla Ice Cream (1L)', category='dairy', price=280, stock=160, description='Vanilla ice cream'),
            Product(name='Cottage Cheese (250g)', category='dairy', price=200, stock=140, description='Cottage cheese'),
            Product(name='Sour Cream (200ml)', category='dairy', price=120, stock=150, description='Sour cream'),
            Product(name='Condensed Milk (397g)', category='dairy', price=180, stock=200, description='Sweetened condensed milk'),
            Product(name='Evaporated Milk (340g)', category='dairy', price=120, stock=220, description='Evaporated milk'),
            Product(name='Greek Yogurt (500ml)', category='dairy', price=150, stock=140, description='Greek yogurt'),
            Product(name='Flavored Milk (500ml)', category='dairy', price=90, stock=180, description='Chocolate milk'),
            Product(name='Mozzarella Cheese (200g)', category='dairy', price=280, stock=130, description='Mozzarella cheese'),
            Product(name='Parmesan Cheese (100g)', category='dairy', price=350, stock=100, description='Parmesan cheese'),
            Product(name='Whipping Cream (250ml)', category='dairy', price=180, stock=120, description='Heavy cream'),
            
            # Beverages (30 items)
            Product(name='Coca Cola (500ml)', category='beverages', price=60, stock=400, description='Coke soda'),
            Product(name='Fanta Orange (500ml)', category='beverages', price=60, stock=380, description='Orange soda'),
            Product(name='Sprite (500ml)', category='beverages', price=60, stock=370, description='Lemon soda'),
            Product(name='Mineral Water (500ml)', category='beverages', price=30, stock=500, description='Bottled water'),
            Product(name='Mixed Fruit Juice (1L)', category='beverages', price=120, stock=250, description='Mixed fruit juice'),
            Product(name='Fresh Mango Juice (500ml)', category='beverages', price=70, stock=280, description='Fresh mango juice'),
            Product(name='Instant Coffee (100g)', category='beverages', price=180, stock=200, description='Instant coffee'),
            Product(name='Kenya Tea Leaves (250g)', category='beverages', price=120, stock=250, description='Kenya tea leaves'),
            Product(name='Hot Chocolate (250g)', category='beverages', price=200, stock=180, description='Chocolate drink'),
            Product(name='Energy Drink (250ml)', category='beverages', price=150, stock=200, description='Energy booster'),
            Product(name='Bottled Water (1.5L)', category='beverages', price=50, stock=450, description='Drinking water'),
            Product(name='Apple Juice (1L)', category='beverages', price=150, stock=220, description='Apple juice'),
            Product(name='Fresh Orange Juice (1L)', category='beverages', price=140, stock=230, description='Fresh orange juice'),
            Product(name='Pineapple Juice (1L)', category='beverages', price=130, stock=210, description='Pineapple juice'),
            Product(name='Ginger Tea Bags (20)', category='beverages', price=180, stock=190, description='Ginger tea bags'),
            Product(name='Green Tea Bags (20)', category='beverages', price=200, stock=180, description='Green tea'),
            Product(name='Fresh Lemonade (500ml)', category='beverages', price=80, stock=240, description='Fresh lemonade'),
            Product(name='Chocolate Milkshake (500ml)', category='beverages', price=120, stock=190, description='Chocolate milkshake'),
            Product(name='Natural Coconut Water (500ml)', category='beverages', price=100, stock=200, description='Natural coconut water'),
            Product(name='Passion Juice (500ml)', category='beverages', price=90, stock=210, description='Passion fruit juice'),
            Product(name='Pepsi (500ml)', category='beverages', price=60, stock=350, description='Pepsi cola'),
            Product(name='Mountain Dew (500ml)', category='beverages', price=60, stock=320, description='Mountain dew'),
            Product(name='Mirinda (500ml)', category='beverages', price=60, stock=310, description='Mirinda orange'),
            Product(name='Stoney Tangawizi (500ml)', category='beverages', price=60, stock=340, description='Ginger drink'),
            Product(name='Alvaro Juice (500ml)', category='beverages', price=80, stock=250, description='Mixed fruit'),
            Product(name='Krest Soda (500ml)', category='beverages', price=50, stock=300, description='Soda water'),
            Product(name='Iced Coffee (500ml)', category='beverages', price=120, stock=180, description='Cold coffee'),
            Product(name='Strawberry Juice (1L)', category='beverages', price=150, stock=160, description='Strawberry juice'),
            Product(name='Guava Juice (500ml)', category='beverages', price=90, stock=190, description='Guava juice'),
            Product(name='Herbal Tea (20 bags)', category='beverages', price=180, stock=150, description='Mixed herbs tea'),
            
            # Snacks (30 items)
            Product(name='Potato Crisps (150g)', category='snacks', price=100, stock=300, description='Potato crisps'),
            Product(name='Assorted Biscuits (300g)', category='snacks', price=120, stock=280, description='Assorted biscuits'),
            Product(name='Roasted Peanuts (250g)', category='snacks', price=80, stock=250, description='Roasted peanuts'),
            Product(name='Butter Popcorn (100g)', category='snacks', price=50, stock=260, description='Butter popcorn'),
            Product(name='Milk Chocolate Bar', category='snacks', price=80, stock=300, description='Milk chocolate'),
            Product(name='Mixed Sweets (200g)', category='snacks', price=60, stock=280, description='Mixed sweets'),
            Product(name='Mint Chewing Gum (pack)', category='snacks', price=40, stock=320, description='Mint chewing gum'),
            Product(name='Chocolate Cake (slice)', category='snacks', price=100, stock=180, description='Chocolate cake'),
            Product(name='Chocolate Chip Cookies (200g)', category='snacks', price=140, stock=220, description='Chocolate chip cookies'),
            Product(name='Salted Crackers (200g)', category='snacks', price=90, stock=240, description='Salted crackers'),
            Product(name='Salty Pretzels (150g)', category='snacks', price=110, stock=200, description='Salty pretzels'),
            Product(name='Mixed Nuts (250g)', category='snacks', price=200, stock=190, description='Mixed nuts'),
            Product(name='Energy Granola Bars (pack 6)', category='snacks', price=180, stock=210, description='Energy bars'),
            Product(name='Fruit Roll (pack)', category='snacks', price=70, stock=230, description='Fruit snack roll'),
            Product(name='Nacho Corn Chips (150g)', category='snacks', price=120, stock=240, description='Nacho chips'),
            Product(name='Plain Rice Cakes (pack)', category='snacks', price=100, stock=200, description='Plain rice cakes'),
            Product(name='Trail Mix (200g)', category='snacks', price=180, stock=180, description='Nuts and dried fruit'),
            Product(name='Dried Beef Jerky (50g)', category='snacks', price=150, stock=170, description='Dried beef snack'),
            Product(name='Cheese Puffs (100g)', category='snacks', price=90, stock=250, description='Cheese snack'),
            Product(name='Vegetable Samosas (pack 4)', category='snacks', price=80, stock=200, description='Vegetable samosas'),
            Product(name='Cashew Nuts (200g)', category='snacks', price=280, stock=160, description='Roasted cashews'),
            Product(name='Macadamia Nuts (150g)', category='snacks', price=350, stock=120, description='Premium macadamia'),
            Product(name='Plantain Chips (150g)', category='snacks', price=90, stock=210, description='Crispy plantain'),
            Product(name='Beef Samosas (pack 4)', category='snacks', price=100, stock=190, description='Beef samosas'),
            Product(name='Chapati Crisps (100g)', category='snacks', price=70, stock=220, description='Chapati snack'),
            Product(name='Honey Roasted Peanuts (250g)', category='snacks', price=100, stock=200, description='Sweet peanuts'),
            Product(name='Cheese Balls (150g)', category='snacks', price=100, stock=230, description='Cheese snack balls'),
            Product(name='Coconut Biscuits (200g)', category='snacks', price=100, stock=210, description='Coconut cookies'),
            Product(name='Dark Chocolate Bar', category='snacks', price=120, stock=180, description='Dark chocolate'),
            Product(name='White Chocolate Bar', category='snacks', price=120, stock=170, description='White chocolate'),
            
            # Bakery (15 items)
            Product(name='White Bread Fresh (400g)', category='bakery', price=50, stock=300, description='Fresh white bread'),
            Product(name='Brown Bread Whole Wheat (400g)', category='bakery', price=60, stock=280, description='Whole wheat bread'),
            Product(name='Soft Chapati (pack 5)', category='bakery', price=100, stock=250, description='Soft chapatis'),
            Product(name='Sweet Mandazi (pack 6)', category='bakery', price=60, stock=260, description='Sweet mandazi'),
            Product(name='Sugar Doughnuts (pack 6)', category='bakery', price=120, stock=200, description='Sugar doughnuts'),
            Product(name='Butter Croissants (pack 4)', category='bakery', price=150, stock=180, description='Butter croissants'),
            Product(name='Soft Buns (pack 6)', category='bakery', price=80, stock=240, description='Soft buns'),
            Product(name='Ready Pizza Base', category='bakery', price=100, stock=190, description='Ready pizza base'),
            Product(name='Pita Bread (pack 6)', category='bakery', price=90, stock=200, description='Pita pockets'),
            Product(name='French Loaf Crispy', category='bakery', price=70, stock=220, description='Crispy French bread'),
            Product(name='Bagels (pack 4)', category='bakery', price=120, stock=160, description='Plain bagels'),
            Product(name='English Muffins (pack 6)', category='bakery', price=100, stock=170, description='English muffins'),
            Product(name='Cinnamon Rolls (pack 4)', category='bakery', price=150, stock=140, description='Sweet cinnamon rolls'),
            Product(name='Garlic Bread', category='bakery', price=80, stock=180, description='Garlic butter bread'),
            Product(name='Brioche Buns (pack 4)', category='bakery', price=140, stock=150, description='Soft brioche'),
            
            # Flour & Grains (20 items)
            Product(name='Maize Flour Sifted (2kg)', category='flour', price=180, stock=350, description='Unga wa mahindi'),
            Product(name='All Purpose Wheat Flour (2kg)', category='flour', price=200, stock=320, description='All purpose flour'),
            Product(name='Pishori Rice (2kg)', category='grains', price=250, stock=300, description='Pishori rice'),
            Product(name='Spaghetti Pasta (500g)', category='grains', price=120, stock=280, description='Spaghetti pasta'),
            Product(name='Rolled Oats (500g)', category='grains', price=150, stock=240, description='Rolled oats'),
            Product(name='Chapati Atta Flour (2kg)', category='flour', price=220, stock=250, description='Chapati flour'),
            Product(name='Self-Raising Flour (1kg)', category='flour', price=140, stock=260, description='Baking flour'),
            Product(name='Instant Noodles (pack)', category='grains', price=40, stock=400, description='Instant noodles'),
            Product(name='Corn Starch (1kg)', category='flour', price=120, stock=280, description='Corn starch'),
            Product(name='Wimbi Millet Flour (1kg)', category='flour', price=150, stock=200, description='Wimbi flour'),
            Product(name='Mtama Sorghum Flour (1kg)', category='flour', price=140, stock=190, description='Mtama flour'),
            Product(name='Rice Flour Ground (500g)', category='flour', price=100, stock=220, description='Ground rice'),
            Product(name='Pearl Barley (500g)', category='grains', price=130, stock=180, description='Pearl barley'),
            Product(name='Instant Couscous (500g)', category='grains', price=180, stock=170, description='Instant couscous'),
            Product(name='White Quinoa (500g)', category='grains', price=350, stock=150, description='White quinoa'),
            Product(name='Basmati Rice (2kg)', category='grains', price=350, stock=200, description='Basmati rice'),
            Product(name='Brown Rice (2kg)', category='grains', price=280, stock=180, description='Brown rice'),
            Product(name='Macaroni Pasta (500g)', category='grains', price=130, stock=250, description='Macaroni pasta'),
            Product(name='Penne Pasta (500g)', category='grains', price=140, stock=240, description='Penne pasta'),
            Product(name='Vermicelli (500g)', category='grains', price=110, stock=220, description='Thin noodles'),
            
            # Spices (20 items)
            Product(name='Table Salt (500g)', category='spices', price=40, stock=400, description='Table salt'),
            Product(name='Ground Black Pepper (50g)', category='spices', price=80, stock=250, description='Ground black pepper'),
            Product(name='Curry Powder Mix (50g)', category='spices', price=100, stock=240, description='Curry spice mix'),
            Product(name='Ground Turmeric (50g)', category='spices', price=90, stock=230, description='Ground turmeric'),
            Product(name='Cumin Seeds (50g)', category='spices', price=110, stock=220, description='Cumin seeds'),
            Product(name='Cinnamon Sticks (50g)', category='spices', price=100, stock=210, description='Cinnamon sticks'),
            Product(name='Smoked Paprika (50g)', category='spices', price=120, stock=200, description='Smoked paprika'),
            Product(name='Hot Chili Powder (50g)', category='spices', price=80, stock=240, description='Hot chili powder'),
            Product(name='Italian Mixed Herbs (30g)', category='spices', price=100, stock=190, description='Italian herbs'),
            Product(name='Green Cardamom (30g)', category='spices', price=150, stock=180, description='Green cardamom'),
            Product(name='Whole Cloves (30g)', category='spices', price=120, stock=190, description='Whole cloves'),
            Product(name='Ground Nutmeg (30g)', category='spices', price=130, stock=170, description='Ground nutmeg'),
            Product(name='Dry Bay Leaves (20g)', category='spices', price=80, stock=200, description='Dry bay leaves'),
            Product(name='Dry Thyme (20g)', category='spices', price=90, stock=180, description='Dry thyme'),
            Product(name='Dry Oregano (20g)', category='spices', price=90, stock=180, description='Dry oregano'),
            Product(name='Garam Masala (50g)', category='spices', price=120, stock=170, description='Indian spice mix'),
            Product(name='Crushed Red Pepper (50g)', category='spices', price=100, stock=190, description='Chili flakes'),
            Product(name='Garlic Powder (50g)', category='spices', price=100, stock=200, description='Garlic powder'),
            Product(name='Onion Powder (50g)', category='spices', price=100, stock=200, description='Onion powder'),
            Product(name='Mixed Spice (50g)', category='spices', price=110, stock=180, description='Baking spice'),
            
            # Cooking Oil (12 items)
            Product(name='Vegetable Cooking Oil (2L)', category='cooking_oil', price=450, stock=300, description='Vegetable cooking oil'),
            Product(name='Extra Virgin Olive Oil (500ml)', category='cooking_oil', price=650, stock=180, description='Extra virgin olive oil'),
            Product(name='Pure Sunflower Oil (1L)', category='cooking_oil', price=280, stock=250, description='Pure sunflower oil'),
            Product(name='Virgin Coconut Oil (500ml)', category='cooking_oil', price=400, stock=190, description='Virgin coconut oil'),
            Product(name='Red Palm Oil (1L)', category='cooking_oil', price=300, stock=200, description='Red palm oil'),
            Product(name='Pure Sesame Oil (250ml)', category='cooking_oil', price=350, stock=160, description='Pure sesame oil'),
            Product(name='Canola Cooking Oil (1L)', category='cooking_oil', price=320, stock=220, description='Canola cooking oil'),
            Product(name='Pure Avocado Oil (250ml)', category='cooking_oil', price=550, stock=150, description='Pure avocado oil'),
            Product(name='Vegetable Oil (1L)', category='cooking_oil', price=240, stock=280, description='Cooking oil'),
            Product(name='Groundnut Oil (1L)', category='cooking_oil', price=300, stock=190, description='Peanut oil'),
            Product(name='Corn Oil (1L)', category='cooking_oil', price=280, stock=200, description='Corn oil'),
            Product(name='Blended Oil (2L)', category='cooking_oil', price=400, stock=240, description='Mixed vegetable oil'),
            
            # Household (18 items)
            Product(name='Soft Toilet Paper (4 rolls)', category='household', price=150, stock=300, description='Soft tissue'),
            Product(name='Bathing Soap Bar (pack 3)', category='household', price=120, stock=350, description='Bathing soap'),
            Product(name='Washing Detergent (1kg)', category='household', price=180, stock=280, description='Washing powder'),
            Product(name='Dishwashing Liquid (500ml)', category='household', price=100, stock=300, description='Dishwashing liquid'),
            Product(name='Cleaning Bleach (1L)', category='household', price=120, stock=250, description='Cleaning bleach'),
            Product(name='Room Air Freshener (300ml)', category='household', price=200, stock=200, description='Room spray'),
            Product(name='Safety Matches (box)', category='household', price=20, stock=500, description='Safety matches'),
            Product(name='White Candles (pack 5)', category='household', price=100, stock=280, description='White candles'),
            Product(name='Heavy Duty Garbage Bags (20 pcs)', category='household', price=120, stock=250, description='Heavy duty bags'),
            Product(name='Kitchen Sponges (pack 3)', category='household', price=80, stock=300, description='Kitchen sponges'),
            Product(name='Floor Broom', category='household', price=200, stock=200, description='Floor broom'),
            Product(name='Wet Mop', category='household', price=250, stock=180, description='Wet mop'),
            Product(name='Hangers Plastic (pack 10)', category='household', price=150, stock=220, description='Clothes hangers'),
            Product(name='Floor Wipes (pack 50)', category='household', price=180, stock=190, description='Cleaning wipes'),
            Product(name='Laundry Basket', category='household', price=300, stock=150, description='Plastic basket'),
            Product(name='Plastic Bucket (20L)', category='household', price=250, stock=180, description='Water bucket'),
            Product(name='Disinfectant (1L)', category='household', price=180, stock=210, description='Surface disinfectant'),
            Product(name='Hand Soap (500ml)', category='household', price=120, stock=260, description='Liquid hand soap'),
        ]
        
        db.session.bulk_save_objects(products)
        db.session.commit()
        print(f"✅ Successfully seeded {len(products)} products!")

if __name__ == '__main__':
    seed_products()